### PR TITLE
Remove spaces after commas globally

### PR DESCRIPTION
**Pull request by Gatzy118**
When preparing erlc_opts, remove all comma/whitespace pairs instead of
just the first

### CODE REVIEW

**Comment by essen** [comment]
Thanks.

I need tests before I merge, otherwise this will have to wait. :-)

**Comment by Gatzy118** [comment]
Took a look at failing tests, seem unrelated. Are they known to be failing?

**Comment by essen** [comment]
I know there's a few things that fail on CI that don't here. If "make check c=core-compat" works on your machine, don't worry about it.

**Comment by Gatzy118** [comment]
Yes, that runs fine

**Comment by essen** [comment]
Merged, thanks!

**Pull request merged**
