### PR TITLE
Add package geas to the index

### PR DESCRIPTION
**Pull request by crownedgrouse**

### CODE REVIEW

**Comment by crownedgrouse** [comment]
Hi Loïc, 
Sorry to bother you, you are probably very busy, but could package index addition be merged in a relative short delay ? Some other of my projects are depending on this package... Not a big issue, yeah and dependancies can be set anyway, but will need changes in Makefiles then.

**Comment by essen** [comment]
Hey, I usually do, looks like I forgot this one.

**Comment by essen** [comment]
There you go!

**Comment by crownedgrouse** [comment]
Hi, thanks !
I knew it was unusual... ;-)

**Pull request merged**
