### PR TITLE
Add package PGO to index

### PR DESCRIPTION
**Pull request by telsgaard**
Added package PGO to index

### CODE REVIEW

**Comment by essen** [comment]
Ah right the `~>` stuff makes it break. Well let me fix that and add it to the index anyway.

**Comment by telsgaard** [comment]
Thanks, I can get it working if i add all 3 packages, and then in the Makefile depends on each of them like: DEPS = backoff opencensus pgo

But not with only pgo in DEPS, does that require backoff and opencensus to have an Makefile ?

PACKAGES += pgo
pkg_pgo_name = pgo
pkg_pgo_description = Erlang Postgres client and connection pool
pkg_pgo_homepage = https://github.com/erleans/pgo.git
pkg_pgo_fetch = git
pkg_pgo_repo = https://github.com/erleans/pgo.git
pkg_pgo_commit = master

PACKAGES += backoff
pkg_backoff_name = backoff
pkg_backoff_description = Simple exponential backoffs in Erlang
pkg_backoff_homepage = https://github.com/ferd/backoff.git
pkg_backoff_fetch = git
pkg_backoff_repo = https://github.com/ferd/backoff.git
pkg_backoff_commit = master

PACKAGES += opencensus
pkg_opencensus_name = opencensus
pkg_opencensus_description = A stats collection and distributed tracing framework
pkg_opencensus_homepage = https://github.com/census-instrumentation/opencensus-erlang.git
pkg_opencensus_fetch = git
pkg_opencensus_repo = https://github.com/census-instrumentation/opencensus-erlang.git
pkg_opencensus_commit = master

**Comment by essen** [comment]
No it's because Erlang.mk is not implementing something and that causes the fetching of backoff and opencensus to fail. I'll work on it over the holidays. Glad you got a workaround for now though!

**Comment by essen** [comment]
I've just pushed aaa94f3 that fixes pgo. Enjoy!

**Comment by telsgaard** [comment]
Thanks! You are doing an amazing job with erlang.mk!! my favourite build
tool

Thomas

man. 31. dec. 2018 kl. 11.15 skrev Loïc Hoguin <notifications@github.com>:

**Pull request closed without merging**
