### PR TITLE
The '-r' option of 'xargs' is illegal on OSX

### PR DESCRIPTION
**Pull request by manifest**
```
 DEP    cowboy
xargs: illegal option -- r
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]
```

### CODE REVIEW

**Comment by essen** [comment]
Thanks, I'll try it in a few days, I can't access my OSX test VM at the moment. :-)

**Comment by danielwhite** [comment]
Can confirm this works for me.

Funnily enough, when building cowboy, this ends up resulting in an error that looks a lot like ninenines/cowboy#842.

**Comment by danielwhite** [comment]
As an aside, I think this might be unnecessarily complicated. GNU xargs works perfectly fine without the `-r` option/

Commit 75453090 introduced the flag, and mentioned FreeBSD. Is this flag actually needed for FreeBSD support?

**Comment by manifest** [comment]
According to the man page, the -r option does nothing in the FreeBSD version of xargs.

```
     -r	     Compatibility with	GNU xargs.  The	GNU version of xargs runs the
	     utility argument at least once, even if xargs input is empty, and
	     it	supports a -r option to	inhibit	this behavior.	The FreeBSD
	     version of	xargs does not run the utility argument	on empty
	     input, but	it supports the	-r option for command-line compatibil-
	     ity with GNU xargs, but the -r option does	nothing	in the FreeBSD
	     version of	xargs.
```

**Comment by essen** [comment]
See this commit instead: 0040f93ccd5f4aa6db719741fcd6335c48d1390d

**Comment by essen** [comment]
The -r option was added so that it works on both, but I guess OSX is even more different. :-)

**Comment by manifest** [comment]
I don't see any description, even mention of the `-r`  option of xargs utility on OSX. But it looks like its BSD version works the same way as GNU xargs works with `-r` options. If the standard input doesn't contain any nonblanks, the command won't be run. As for OSX, they doesn't just ignore the `-r` option as FreeBSD does, they drop it completely out.

I run a simple test which, I think, confirms that.
```sh
## Linux

$ ls -1
1

$ find . -name 1 | xargs echo '--xargs utility has been run--';
--xargs utility has been run-- ./1

$ find . -name 2 | xargs echo '--xargs utility has been run--';
--xargs utility has been run--

$ find . -name 2 | xargs -r echo '--xargs utility has been run--';
$



## OSX

$ ls -1
1

$ find . -name 1 | xargs echo '--xargs utility has been run--';
--xargs utility has been run-- ./1

$ find . -name 2 | xargs echo '--xargs utility has been run--';
$

$ find . -name 2 | xargs -r echo '--xargs utility has been run--';
xargs: illegal option -- r
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]
$
```

**Comment by essen** [comment]
Well, considering xargs is called exactly one time in the whole file, and that find has an --exec option, perhaps we should just drop xargs and use --exec as it looks like a better solution for portability.

**Comment by manifest** [comment]
I think, it's a good idea. :)

**Comment by manifest** [comment]
Made another pull request replacing `xargs` by `find -exec`.

**Comment by essen** [comment]
Closing this considering the other PR looks good. Still no SSH access though so not merging just yet. Just bored, closing tickets. :-)

**Pull request closed without merging**
