### PR TITLE
[Fix #497] Support for hex package names

### LINKED ISSUE #497: Support for hex.pm packages
In `hex` fetcher, allow users to specify the name of the package (which can be different than the associated application):

In the following example `aleppo` is the name of the application and `inaka_aleppo` the package:

```
DEPS = aleppo
dep_aleppo = hex 0.9.9 inaka_aleppo 
```

### PR DESCRIPTION
**Pull request by elbrujohalcon**
[Fix #497] Support for hex package names

### CODE REVIEW

**Comment by elbrujohalcon** [comment]
@essen I'm not sure those errors are produced by my changes… are they?

**Comment by essen** [comment]
Probably not. If "make check c=core" works for you, don't worry.

**Comment by elbrujohalcon** [comment]
@essen `make check c=core` blocks forever at…
```
core-deps-fetch-svn: Bootstrap a new OTP library named test_core_deps_fetch_svn
core-deps-fetch-svn: Add Cowlib 1.0.0 to the list of dependencies
core-deps-fetch-svn: Build the application
```
…any clue on what can I be doing wrong here?

**Comment by elbrujohalcon** [comment]
@essen it works! I took the chance and added tests for the new functionality :)

**Comment by elbrujohalcon** [comment]
@essen any plans on how this will be merged? Anything else I need to do for that?

**Comment by essen** [comment]
Just need to squash I think.

I'll try to do a merge run at the end of the week. Can't promise anything right now, personal stuff.

**Comment by elbrujohalcon** [comment]
@essen squashed, it is.

**Comment by elbrujohalcon** [comment]
@essen : after-erlang-factory ping :trollface:

**Comment by essen** [comment]
I will dedicate one day to merging user contributions this week, but today is not the day.

**Comment by essen** [comment]
So as mentioned on #529 I think first we need to have the == hardcoded and on position 2, and then this new argument would be on position 4.

**Comment by essen** [comment]
@elbrujohalcon @glejeune I think the Hex related development would progress a lot faster if it happened in the hexpm plugin. I propose to do the following for the time being:

* Remove the hex functionality from Erlang.mk (except autopatch, see next point)
* Autoload the hexpm plugin when a fetch method "hex" is detected
* Add a warning when the 2-word form of "hex" is detected (see below).
* (I think a warning is also in order when the older "git" forms are detected.)

This change would avoid duplicating development between hex/hexpm. On the other hand the plugin has to support the "hex" fetch method. I recommend making hex exactly like hexpm (maybe an alias) except when the dep_$1 line has only 2 words (example "hex 1.0") where "==" is implied. This is only for compatibility and could be removed in a few months. The warning would speed up the change.

From that point onward, it's a wait and see game. Development wouldn't be hampered by my busy schedule, and we can later decide if it should stay a pure plugin or should be part of the core.

Thoughts?

**Comment by essen** [comment]
By the way in addition to what I said, I would also change autopatch to use "hex == $(VERSION)", so the 2-words "hex" stuff wouldn't be there for long.

**Comment by elbrujohalcon** [comment]
This PR is a bit old, I think I'll just close it :trollface:

**Pull request closed without merging**
