### PR TITLE
Update bootstrap.mk

### PR DESCRIPTION
**Pull request by marcinurbanski**
Add possibility to use project with dash between (foo-project1)

### CODE REVIEW

**Comment by essen** [comment]
That's wrong because when Erlang sees a folder called `foo-project1` in `ERL_LIBS` it thinks the application is named `foo` and `project1` is its version.

**Comment by marcinurbanski** [comment]
So is it not possible to use dash separated project name?

**Comment by essen** [comment]
Not to my knowledge. Some things will work, some will break. Use underscores instead.

**Comment by marcinurbanski** [comment]
Ok. Thanks for quick explanation. Have nice day!

**Comment by essen** [comment]
Enjoy!

**Pull request closed without merging**
