### PR TITLE
.gitignore: Ignore Vim .swp files

### PR DESCRIPTION
**Pull request by dumbbell**

### CODE REVIEW

**Comment by essen** [comment]
Wow, sorry, I just removed the file. Probably won't merge cleanly anymore. :-)

**Comment by dumbbell** [comment]
I updated the pull request with only the change to `.gitignore`.

**Comment by essen** [comment]
As for adding these to gitignore, I actually like to see in "git status" them because then I can either remove in one go (not have to deal with vim) or find what I might have lost if the computer shut down previously. So I won't be merging. :-) Sorry for the waste of time.

**Comment by dumbbell** [comment]
That's ok, I understand :)

**Pull request closed without merging**
