### PR TITLE
Double colon for source files

### PR DESCRIPTION
**Pull request by dumbbell**

### CODE REVIEW

**Comment by essen** [comment]
Incidentally, this leftover touch was also making things twice slower. Pretty cool!

**Comment by essen** [comment]
OK, thought so, there's still some issues.

Try touching an include file, and then run 'make' again. It won't be detected properly, despite the dep file having the rule.

That's probably why the touch erl files was there.

**Comment by dumbbell** [comment]
I believe the commit I just added address the "try touching an include file" problem.

Now, `$(PROJECT).d` only lists files having dependencies. The rules run `touch` on them.

**Comment by essen** [comment]
Pushed a few more changes, including merging of this (before the extra commit, since I had that already, though in my case it was making an infinite loop :-) until I remove ::).

I need to do further testing but I think this is looking good.

Thanks!

**Pull request closed without merging**
