### PR TITLE
Add CT_LOGS_DIR

### PR DESCRIPTION
**Pull request by nevar**
See https://github.com/ninenines/erlang.mk/pull/593#issuecomment-257118610

### CODE REVIEW

**Comment by essen** [comment]
Looks good, tests pass. Will merge soon. Thanks!

**Comment by essen** [comment]
Realized that docs are missing! Can you add a mention to this new variable to the documentation? It needs to mention the default value also.

**Comment by nevar** [comment]
Review docs for CT_LOGS_DIR.

**Comment by essen** [comment]
Cheers.

**Comment by essen** [comment]
Merged, thanks!

**Pull request closed without merging**
