### PR TITLE
fix: replace perl usage with coreutils

### PR DESCRIPTION
**Pull request by pinicarus**
This should replace the dependency to perl

### CODE REVIEW

**Comment by essen** [comment]
Sounds good. Thanks!

**Comment by essen** [comment]
Merged, thanks!

**Comment by essen** [comment]
I have to revert this commit because `realpath` is not available on macOS by default.

**Comment by pinicarus** [comment]
> I have to revert this commit because `realpath` is not available on macOS by default.

Oh, too bad.

**Comment by essen** [comment]
Would be open to another (reasonable) solution of course.

**Comment by crownedgrouse** [comment]
"readlink - f " can be used when realpath is missing

**Comment by pinicarus** [comment]
> "readlink - f " can be used when realpath is missing

Yes, but it lacks the `--relative-to` feature.

**Comment by pinicarus** [comment]
I have an alternative implementation that uses make's `abspath` (or `realpath`) function and an awk script that only needs the `split` function.

Running it on my laptop with the `--posix` flag gives the same output as `realpath`.
Do you known it `awk` is available in macOS by default?

**Comment by essen** [comment]
Not sure about "by default" but the problem with awk is there's an alternative implementation that might not be compatible, used in Busybox distros for example. That said, GNU awk is required to even build Erlang.mk and the only problem was Alpine (where it's listed as a mandatory dependency in the user guide) so it's probably safe to use.

**Pull request closed without merging**
