### PR TITLE
core/deps.mk: New targets `fetch-deps` and `list-deps` to fetch/list deps recurvively

### PR DESCRIPTION
**Pull request by dumbbell**
Therefore, it lists direct dependencies, dependencies' dependencies, and so on.

### CODE REVIEW

**Comment by dumbbell** [comment]
This push request is ready for review. Sorry, I changed it several times after the initial push.

**Comment by ash-lshift** [comment]
This doesn't work for deps which use rebar because it is `test -f`-ing for `erlang.mk`. `erlang.mk` patches their Makefile but doesn't create an `erlang.mk` alongside it.

**Comment by dumbbell** [comment]
@ash-lshift: Thanks for the report, I changed the patch to check for the inclusion of `erlang.mk` instead.

**Comment by essen** [comment]
Something must be wrong. When I test this on the RabbitMQ umbrella, running "make list-deps" takes about a minute.

**Comment by dumbbell** [comment]
I believe the performance issue is now fixed. Also, the code is much simpler.

The problem was that `list-deps` called `fetch-deps` recursively, the latter being also recursive. This led to way too much repository traversals for doing the same thing all over again. Now, `fetch-deps` fills a single output file which is just printed to stdout by `list-deps`.

The patch is ready for another review.

**Comment by essen** [comment]
Running CI now.

**Comment by essen** [comment]
Tests still good.

**Comment by essen** [comment]
I will try it manually on a couple projects but otherwise it should be good.

**Comment by dumbbell** [comment]
Cool, thanks! If you are ok with the behavior and naming, I will write some documentation.

**Comment by essen** [comment]
I'm fine with it. In the future we'll probably want a "make show-deps" to have some details about each dep, but that functionality would have to be built on top of this patch.

Waiting for docs then!

**Comment by dumbbell** [comment]
Do you mean `show-deps` would print more detailed informations, compared to the simple list printed by `list-deps`?

**Comment by dumbbell** [comment]
I added new section to `deps.asciidoc`.

**Comment by essen** [comment]
Merged, thanks!

**Pull request closed without merging**
