### PR TITLE
Fix for bcrypt compilation on OSX El Capitan

### PR DESCRIPTION
**Pull request by elbrujohalcon**

### CODE REVIEW

**Comment by essen** [comment]
Quick look confirms this works. Doing a full run with your patch now. Can you make it a single commit?

**Comment by essen** [comment]
Full run worked and also fixed erlpass and ierlang. Just need a good squash now.

**Comment by elbrujohalcon** [comment]
sqashed :+1:

**Comment by essen** [comment]
I have a last full run currently running, this time on Linux, and then it should be good.

**Comment by essen** [comment]
Merged, thanks!

**Pull request closed without merging**
