### PR TITLE
plugins/escript.mk: Remove $(ESCRIPT_FILE) in distclean-escript

### PR DESCRIPTION
**Pull request by dumbbell**
... not `$(ESCRIPT_NAME)`, which can be set to another value.

### CODE REVIEW

**Comment by essen** [comment]
Should probably improve a test with a check that it gets removed before merging.

**Comment by dumbbell** [comment]
Ok, I will add one.

**Comment by dumbbell** [comment]
Done!

**Comment by essen** [comment]
Tests are good.

**Comment by essen** [comment]
Merged, to be pushed in a few. Thanks!

**Pull request closed without merging**
