### PR TITLE
Add package erlangzmq to the index

### PR DESCRIPTION
**Pull request by drozzy**
Resubmitting PR for erlangzmq with dialyzer warnings fixed.

### CODE REVIEW

**Comment by drozzy** [comment]
Sorry, but I'm having a hard time understanding the CI output. Could you let me know what's not working?

I'm not sure if I mentioned, but this uses Erlang/OTP 19.

**Comment by essen** [comment]
Don't worry about CI. All I care about is that 'make check p=erlangzmq' works. If it does, then this can be merged.

**Comment by drozzy** [comment]
Oh ok. Did it work?
Just out of curiosity what does that check?

**Comment by essen** [comment]
It checks that the package compiles and loads properly. And it did. Merged, thanks!

**Pull request merged**
