### PR TITLE
Add possibility to specify custom ErlyDTL options

### PR DESCRIPTION
**Pull request by KrzysiekJ**

### CODE REVIEW

**Comment by essen** [comment]
Thanks. Look at what we did for EUNIT_OPTS, it's better if we don't have to provide the [].

**Comment by KrzysiekJ** [comment]
Right, fixed. (Also updated the README to not suggest that brackets are needed).

**Comment by essen** [comment]
Thanks. Patch looks good. I'll get back to you about merging when I get to ErlyDTL, currently adding tests and improved docs for everything.

**Comment by elbrujohalcon** [comment]
@essen any ETA for merging this one?

**Comment by essen** [comment]
No tests, no ETA. :-)

Feel free to open a new PR with this patch and a test.

**Comment by KrzysiekJ** [comment]
I’ve updated the pull request to include a test.

**Comment by essen** [comment]
Running the tests, don't worry too much about the reports from github.

**Comment by essen** [comment]
Looks fine in CI. Will not have time until this week-end but feel free to ping me by then so I don't forget.

**Comment by essen** [comment]
Can we make it DTL_OPTS instead of ERLYDTL_OPTS? Not much point being verbose there.

**Comment by KrzysiekJ** [comment]
Sure, changed.

**Comment by essen** [comment]
Merged, thanks!

**Pull request merged**
