### PR TITLE
fix manual specification of deps

### LINKED ISSUE #306: specifying local dependencies fails
Hi,

trying to specify a local dependency
```
  2 DEPS = dc_common
  3 dep_dc_common = cp ../dc_common/
```
fails with `ERLANG_MK_VERSION = 1.2.0-631-g56cbd9e`.

V=1 make output
```
mkdir -p /home/winlu/gitrepos/dist_calc/distr_controller/node/deps
if [ "git" = "git" ]; then git clone -q -n --  cp /home/winlu/gitrepos/dist_calc/distr_controller/node/deps/dc_common; cd /home/winlu/gitrepos/dist_calc/distr_controller/node/deps/dc_common && git checkout -q  ../dc_common/; elif [ "git" = "hg" ]; then hg clone -q -U  cp /home/winlu/gitrepos/dist_calc/distr_controller/node/deps/dc_common; cd /home/winlu/gitrepos/dist_calc/distr_controller/node/deps/dc_common && hg update -q  ../dc_common/; elif [ "git" = "svn" ]; then svn checkout -q  cp /home/winlu/gitrepos/dist_calc/distr_controller/node/deps/dc_common; elif [ "git" = "cp" ]; then cp -R  cp /home/winlu/gitrepos/dist_calc/distr_controller/node/deps/dc_common; elif [ "git" = "hex" ]; then erl +A0 -noinput -boot start_clean -pz /home/winlu/gitrepos/dist_calc/distr_controller/node/.erlang.mk/rebar/ebin -eval "        ssl:start(),    inets:start(),  {ok, {{_, 200, _}, _, Body}} = httpc:request(get,                {\"https://s3.amazonaws.com/s3.hex.pm/tarballs/dc_common-../dc_common/.tar\", []},               [], [{body_format, binary}]),    {ok, Files} = erl_tar:extract({binary, Body}, [memory]), {_, Source} = lists:keyfind(\"contents.tar.gz\", 1, Files),      ok = erl_tar:extract({binary, Source}, [{cwd, \"/home/winlu/gitrepos/dist_calc/distr_controller/node/deps/dc_common\"}, compressed]),    halt()" -- erlang.mk; else echo "Unknown or invalid dependency: dc_common. Please consult the erlang.mk README for instructions." >&2; exit 78; fi
fatal: repository 'cp' does not exist
/bin/sh: line 0: cd: /home/winlu/gitrepos/dist_calc/distr_controller/node/deps/dc_common: No such file or directory
erlang.mk:4529: recipe for target '/home/winlu/gitrepos/dist_calc/distr_controller/node/deps/dc_common' failed
make: *** [/home/winlu/gitrepos/dist_calc/distr_controller/node/deps/dc_common] Error 1
```

### PR DESCRIPTION
**Pull request by ingwinlu**
when a manual dep source was specified, erlang.mk assumed it was a git source.

fix #306 

note: this fails tests (edown), but master does as well so it might not be a valid solution for the problem

### CODE REVIEW

**Comment by essen** [comment]
I see the problem, but this isn't the correct solution unfortunately. :-) I'm afraid we will need to special case cp out, as the 2 words form is an older erlang.mk way of specifying deps (repo commit).

**Comment by ingwinlu** [comment]
I don't see the value of keeping backwards compatibility with older erlang.mk dep specs and think that keeping it around just blows erlang.mk up for no good reason.

If a project used an old version of erlang.mk and that spec format, it would still build with that old version of erlang.mk; if a new project tries to add that spec it is 'wrong' to work in the first place as it should not be specified like that anymore.

Also keep in mind that just a special case for cp would not be enough, as every non-git spec currently fails (hex, ...)

running the testsuite on all indexed packages atm to see which ones would be affected by this PR, but I am on 'holiday' bandwith and cpu, so it might take a few hours.

**Comment by essen** [comment]
Thanks, waiting for the result.

The older format is there so that we are compatible with projects using older erlang.mk. The newer erlang.mk is always used when building because it includes fixes that are required for some functionality (and sometimes just building). This is needed now because changes are still coming in quickly, but I suspect in a couple years we can revert that behavior and just use the local erlang.mk.

**Comment by ingwinlu** [comment]
just keep in mind that it is not your job to fix everything idiots put into their Makefiles and rebar.config's. Sometimes clean code and the possibility to easily sidestep erlang.mk behavior (for example with the manual specs) is way more important then to automagically fix someones bad config.

Projects which use git@github in their deps and have not been touched for a few years are not touched for a reason.

**Comment by essen** [comment]
The thing is the idiot was me, and the issue is in (older) erlang.mk. :-)

This particular case is a fix for a lack of foresight on my part in the past. I also do not believe I will be able to think of everything will be needed in the future. So this way of doing things is best for now.

*However* there are ways to fix the older projects that don't involve keeping the old format of specifying dependencies, so I just need to work on that.

**Comment by ingwinlu** [comment]
```
[winlu@winlu-main test]$ diff pkgs.log.master pkgs.log.fix
10a11
> bullet: make error
59a61
> erldb: make error
62a65
> giallo: make error
70a74
> lambdapad: make error
```
```
[winlu@winlu-main test]$ cat pkgs.log.master 
aberth: make error
amqp_client: make error
antidote: make error
apns: make error
azdht: make error
basho_bench: make error
bitcask: make error
bitstore: make error
boss: make error
boss_db: make error
carotene: make error
cberl: make error
chronos: make error
cl: make error
classifier: make error
cloudi_core: make error
cloudi_service_api_requests: make error
cloudi_service_db: make error
cloudi_service_db_cassandra: make error
cloudi_service_db_cassandra_cql: make error
cloudi_service_db_couchdb: make error
cloudi_service_db_elasticsearch: make error
cloudi_service_db_memcached: make error
cloudi_service_db_mysql: make error
cloudi_service_db_pgsql: make error
cloudi_service_db_riak: make error
cloudi_service_db_tokyotyrant: make error
cloudi_service_filesystem: make error
cloudi_service_http_client: make error
cloudi_service_http_cowboy: make error
cloudi_service_http_elli: make error
cloudi_service_map_reduce: make error
cloudi_service_oauth1: make error
cloudi_service_queue: make error
cloudi_service_quorum: make error
cloudi_service_router: make error
cloudi_service_tcp: make error
cloudi_service_timers: make error
cloudi_service_udp: make error
cloudi_service_validate: make error
cloudi_service_zeromq: make error
cr: make error
dnssd: make error
dtl: make error
edis: make error
ehsa: make error
ejabberd: make error
elli: make error
emysql: make error
epcap: make error
eper: make error
episcina: make error
epubnub: make error
eqm: make error
eredis: make error
eredis_pool: make error
erlang_cep: make error
erlang_js: make error
erlcron: make error
exometer: make error
flower: make error
geef: make error
gold_fever: make error
gossiperl: make error
gun: make error
hanoidb: make error
iota: make error
jerg: make error
joxa: make error
kvs: make error
lasp: make error
lasse: make error
ldap: make error
ling: make error
locker: make error
luwak: make error
mongooseim: make error
nifty: make error
nkbase: make error
oauth2: make error
pqueue: make error
ptrackerl: make error
purity: make error
rabbit: make error
rabbit_exchange_type_riak: make error
radierl: make error
rec2json: make error
riak_core: make error
riak_dt: make error
riak_kv: make error
riak_pg: make error
riak_pipe: make error
riak_sysmon: make error
riak_test: make error
riakc: make error
riakhttpc: make error
riakpool: make error
service: make error
shotgun: make error
spapi_router: make error
statebox_riak: make error
tempo: make error
tirerl: make error
twerl: make error
ucol_nif: make error
uuid: make error
ux: make error
vert: make error
yamler: make error
zeta: make error
```
building the index with R18 unfortunately was not too helpful as a lot of packages don't support it (yet).
However the diff identifies 4 packages with benefit from the fallback.

**Comment by ingwinlu** [comment]
6f8265c409aff5ee626bdc208d64e7e7159c9a86 is not pretty but it should provide the backwards compability you desire.

started a new test run with it now.

**Comment by essen** [comment]
Starting work again (for real this time I HOPE) so I will get back to you soon.

**Comment by ingwinlu** [comment]
hey,

great to hear and sorry to be of no help, I used my branch with the first commit for the one project where I needed it; but did not have time to fix the backwards compability patch so it actually works, I hope you can at least use some of it

**Comment by essen** [comment]
I think I got it.

Basically first we get the fetch method (which is taken either from package or from dep_* line; failure to do that uses the method 'fail'), then we call the function for the fetch method.

This function then calls dep_repo, dep_commit, dep_name as needed, and those of course looking for the repo, commit and name based on the line.

To maintain compatibility, there will be a 'legacy' method which assumes git as the fetch method, and do things the old way.

Will push tomorrow.

**Comment by essen** [comment]
Pushed b985c818ffbb7bd500a74646ad649d78353f21c4. Feedback appreciated. :-)

**Comment by essen** [comment]
Closing as I believe I solved it. Thanks!

**Pull request closed without merging**
