### PR TITLE
Esh.mk plugin

### PR DESCRIPTION
**Pull request by crownedgrouse**
Add a new plugin for powerful, simple, esh template engine.

### CODE REVIEW

**Comment by crownedgrouse** [comment]
`make check p=esh_mk` failed due to .app file missing. Normal, it is only a erlang.mk plugin. Did not find a smart way to mute this error.
Could be smart to tag package that are only a make pluging  not an erlang project.

**Comment by essen** [comment]
See https://github.com/ninenines/erlang.mk/blob/master/test/Makefile#L168

**Comment by crownedgrouse** [comment]
I saw it, but error is raised before L199. This variable is used only L207

**Comment by essen** [comment]
I mean sure if you call it explicitly but that doesn't matter, what matters is that it's not called when calling `make packages`.

**Comment by crownedgrouse** [comment]
Ah ok. Do you mean I need to add this package in this variable anyway?

**Comment by essen** [comment]
Yes please.

**Comment by crownedgrouse** [comment]
https://github.com/ninenines/erlang.mk/blob/master/test/Makefile#L200 could replace 'false' by a test -f xxx/plugins.mk ?

**Comment by crownedgrouse** [comment]
work for me with this fix .  `make check p=esh_mk` does not fails anymore.

**Comment by essen** [comment]
I've merged locally and reverted the `test -f ...` lines. `make check p=...` is meant for Erlang applications. If for example Cowboy failed to build (no .app file) the error would not be detected because Cowboy also has a plugins.mk file. And if I remember correctly plugins are not required to have a `plugins.mk`, the plugin can be loaded from a different location. Will push soon, thanks!

**Pull request closed without merging**
