### PR TITLE
always patch deps that are listed in the autopatch var.

### PR DESCRIPTION
**Pull request by kaos**
This will also address issue #217. At least for the given example repo.

I took a slightly different approach to that suggested in #217, by looking for the `rebar` script instead of always patching.

### CODE REVIEW

**Comment by essen** [comment]
Right but I think if someone puts an application to be autopatched we should really just autopatch it, there's really no reason not to I believe.

**Comment by kaos** [comment]
Yeah, or that :)
 Den 26 mar 2015 14:34 skrev "Loïc Hoguin" <notifications@github.com>:

**Comment by kaos** [comment]
I've updated this PR so it always patches. Also, I needed it to honor the `erl_first_files` option from `rebar.config`, so that's in here too.. ;)

**Comment by essen** [comment]
Do you have an example repository for the erl_first_files?

**Comment by kaos** [comment]
This one, for instance.
https://github.com/knutin/elli

But it may have been another that actually caused me compile time issues..
This one, I think it was: https://github.com/uwiger/parse_trans

**Comment by essen** [comment]
Merged, thanks!

**Pull request merged**
