### PR TITLE
Add support for customized prologue when compiling yecc (yrl) files.

### PR DESCRIPTION
**Pull request by lordnull**
The documentation for erlc allows the use of `-I` to define a custom prologue to use when compiling yacc source files. This is an option available in rebar. However, there does not exist a way to define a custom prologue in erlang.mk. This adds a variable one can set allowing one to not only define a custom prologue, buy any additional erlc options one my want.

### CODE REVIEW

**Comment by essen** [comment]
Wow thanks! And sorry for the late reply, I missed a few things on Github due to email issues. I will run the tests now.

**Comment by essen** [comment]
Tests look good. Failures are unrelated.

**Comment by lordnull** [comment]
I didn't think they were related, but good to know for sure. Thanks for the review :).

**Comment by essen** [comment]
Merged, thanks!

**Pull request closed without merging**
