### PR TITLE
Elixir plugin

### PR DESCRIPTION
**Pull request by deadtrickster**
Elixir files can be placed to src or lib. 
Also this part of Elixir quickstart might be useful: http://elixir-lang.org/crash-course.html#adding-elixir-to-existing-erlang-programs

fix for #223

### CODE REVIEW

**Comment by essen** [comment]
Hey, sorry just thought of this now. We can't do 'lib/' because this conflicts with Erlang's own lib (ERL_LIBS) that I plan to use to enable multi application repositories. Do you think that's problematic if it's not handled?

**Comment by deadtrickster** [comment]
Elixir (well mix) people place their code in lib/ usually. I personally prefer src/ at least for erlang.mk based stuff.

**Comment by essen** [comment]
Yeah but we're not going to compile whole Elixir projects here. Let's start with src/ since that fits your needs and can definitely be useful for the odd module, and then we'll see if people need more.

**Comment by essen** [comment]
Fixed the issue with the cover test suite on master if you want to add a test.

**Comment by essen** [comment]
I think I should also add support for Elixir dependencies.

**Comment by deadtrickster** [comment]
speeking of elixir templates, what you suggestions?

**Comment by zuiderkwast** [comment]
In which way would 'lib/' conflict with ERL_LIBS? ERL_LIBS is a list of directories that contain applications while 'lib/' is a directory inside an application. I can't see how these would conflict.

**Comment by essen** [comment]
I have plans to allow repositories to contain more than one application and ./lib/ would be the default directory (same as OTP).

**Comment by essen** [comment]
For info I can't merge this yet because we are patching rebar out and that breaks the compilation of Elixir. Adding it to #265 for now.

**Comment by michaelklishin** [comment]
@essen this could be quite useful for some future improvements in RabbitMQ, for which Elixir makes more sense. Is this still not ready for merging?

**Comment by essen** [comment]
This probably won't be merged because this exists: https://github.com/botsunit/elixir.mk

Not sure where Elixir would make more sense, so in case it's DSL related take note that this also exists: https://github.com/ninenines/lfe.mk

**Comment by essen** [comment]
Closing in favor of the Elixir plugin. Thanks!

**Pull request closed without merging**
