### PR TITLE
Add support for rebar "raw" deps

### PR DESCRIPTION
**Pull request by zerotao**
rebar deps have support for "raw" packages i.e. packages that are
not intended to be built.  e.g.

{deps, [
  {json_patch_tests, "", {git, "git://github.com/json-patch/json-patch-tests.git"}, [raw]}
]}

This change adds support for those packages
when AUTOPATCHing and as a result also addes support for download only
dependencies at the top level via DEPS_FETCH_ONLY += <package>

### CODE REVIEW

**Comment by essen** [comment]
This will break at least one of the packages in the index I think (but which one, I don't really remember).

**Comment by essen** [comment]
I suppose what we could do *instead* is to detect cases where we clearly don't have an Erlang application, and not do anything when that happens.

What's the application that has this example above?

**Comment by essen** [comment]
By not do anything I mean we create an empty Makefile if none exist to no-op.

**Comment by zerotao** [comment]
I ran into this when integrating https://github.com/talentdeficit/json into a project.  I'm perfectly willing to go with the empty Makefile.

Is the project this would break using 'raw' but expecting it to be built anyway?

**Comment by essen** [comment]
I will have to get back to you on that. I am currently working on improving compatibility and have seen more than a hundred projects today so my memory is a little fuzzy. I will ping the ticket when I know for sure what we need to do.

**Comment by essen** [comment]
I think for now I will detect if there is an src/ folder and if not then put an empty Makefile. How does that sound?

**Comment by zerotao** [comment]
We might also look for an apps folder for the multi app approach but the above works for me.  I would be happy to implement it if you like.

**Comment by essen** [comment]
I don't think apps/ layouts are allowed in dependencies even in rebar. Haven't seen a single one in the near 200 projects that erlang.mk now compiles.

**Comment by zerotao** [comment]
ok, that's reasonable.

**Comment by essen** [comment]
Fixed in c0c2863a21a2eee46c69e5a2ce275c91aa2f2ba3 and the package json added to the index. Thanks!

**Comment by zerotao** [comment]
thanks

**Pull request closed without merging**
