### PR TITLE
Adds DOC_DEPS; fixes #75

### LINKED ISSUE #75: Add DOCS_DEPS
It would be useful for erlang.mk to support dependencies for generating documentation.

My use case is to easily use https://github.com/uwiger/edown.git together with erlang.mk

### PR DESCRIPTION
**Pull request by zuiderkwast**
Implemented in the same way as TEST_DEPS. A test case that generates edoc using edown is included.

### CODE REVIEW

**Comment by essen** [comment]
Most likely won't merge cleanly after my push. :-)

**Comment by zuiderkwast** [comment]
Merge this one first then. :-)

**Comment by essen** [comment]
I'm already in the middle of commits, sorry. Shouldn't be too hard to fix this one anyway, just the copyright line I think.

**Comment by zuiderkwast** [comment]
Don't worry; i'll rebase it.

**Comment by essen** [comment]
Merged, thanks!

**Pull request merged**
