### PR TITLE
core/erlc.mk: added src subfolders support in makedep.erl

### PR DESCRIPTION
**Pull request by okebkal**

### CODE REVIEW

**Comment by essen** [comment]
Hello, the tests you added don't seem to work, except on OSX apparently. Do you have access to a Linux or BSD?

**Comment by okebkal** [comment]
I did the test under Debian Linux. Could you provide more detailed information about the fails?

**Comment by essen** [comment]
I think the failure is because you use echo with \n in it. In the rest of the test suite we use printf to make sure it works everywhere. Try changing this, I'll re-run the tests and see if that fixes it.

**Comment by okebkal** [comment]
Ok, change done, please re-run the test.

**Comment by okebkal** [comment]
I see already some fails here, but could you give me the log details?

**Comment by essen** [comment]
Probably unrelated, I'll get back to you when I get more time.

**Comment by essen** [comment]
Merged locally, thanks!

**Pull request closed without merging**
