### PR TITLE
Include applications `$(APPS_DIR)` in the `list-deps` targets

### PR DESCRIPTION
**Pull request by dumbbell**
In the case of a multi-applications repository, if one application depends on another one (using `$(LOCAL_DEPS)`), it will now be listed in the `list-deps` targets.

### CODE REVIEW

**Comment by essen** [comment]
Need a test that has `LOCAL_DEPS = ssl` or similar to see if it still works in that case (it probably does). Otherwise good. Maybe just add `ssl` to the existing test case.

**Comment by essen** [comment]
Also please add the following to the changelog:

```
2019/06/20: `list-deps` now includes local applications
            found in the `APPS_DIR` directory.
```

**Comment by dumbbell** [comment]
I addressed both comments.

**Comment by essen** [comment]
Will merge tomorrow!

**Comment by essen** [comment]
Merged, thanks!

**Pull request closed without merging**
