### PR TITLE
Update dep_fetch_hex.erl

### PR DESCRIPTION
**Pull request by glejeune**
To be able to use versions' comparators.

Thus, you can use >=, <=, ==, <, > or ~>

Example :

```
dep_cowboy = hex ~> 1.0.0
```

### CODE REVIEW

**Comment by essen** [comment]
Didn't @elbrujohalcon write something for this already?

**Comment by elbrujohalcon** [comment]
@essen I think this is more related to #495 than my work on #497

**Comment by essen** [comment]
Ah yeah. What does this PR even does, anyway? I'm not sure what gets fetched in the above example.

**Comment by glejeune** [comment]
@essen With hex, in the current version of erlang.mk, you can just fetch an exact version for a dependency. With this PR you can use a comparator. For example, `~> 1.0.0` will fetch the max available version in [1.0.0, 1.1.0[. `< 2.0.0` will fetch the max available version, lower than 2.0.0...

**Comment by essen** [comment]
I think you should look into #495 and send a PR to hexer.mk or something.

By the way didn't someone create an "hexpm" fetch method in a plugin? I recall something like this. Maybe my memory is wrong. This probably should go there.

It might also be worth making one repo for all Elixir-related plugins (you can have more than one plugin per repo, and choose to include one or more, see documentation). Food for thoughts.

**Comment by elbrujohalcon** [comment]
@essen I was tempted to create that `hexpm` fetcher, but still haven't found the time for it.

**Comment by elbrujohalcon** [comment]
And I would not consider hex to be _Elixir-related_. I use it a lot and I don't do no Elixir at the time. Just saying.

**Comment by glejeune** [comment]
@essen : OK, so if you prefer a plugin, I'll create one, but do you plan to remove hex from the fetch methods ?

**Comment by essen** [comment]
We need an hex fetch method in Erlang.mk for compatibility with Rebar3.

I'm open with a solution providing a default like we have now (+/- values) and a plugin optionally extending it, or any other solution that makes life easier than having two separate fetch methods with similar purposes.

If you want to work on this do take note of the other PR sent by @elbrujohalcon as it added a value. I don't mind breaking changes if that means we get it right (keeping the compatibility is often easy enough).

If it was smaller, didn't rely on regexps and didn't use maps (Erlang.mk should work with older Erlang versions) I could perhaps be convinced to maintain it. But right now I think it belongs more to a plugin.

**Comment by glejeune** [comment]
OK, we can close, I made a plugin : https://github.com/botsunit/hexpm.mk

**Comment by essen** [comment]
For the sake of user friendliness, I will modify the current hex method to accept exactly `==`. Then switching to the plugin is just a matter of renaming hex to hexpm. So not closing this until my part is done.

**Comment by elbrujohalcon** [comment]
Shouldn't `==` be the default value in hexpm plugin (i.e. It can be omitted)?

**Comment by essen** [comment]
I'd say explicit is better, and having the same values at the same word place is also easier to implement and remember.

**Comment by essen** [comment]
Alternative could be to automatically load the plugin when hex dependencies exist instead of keeping the current code inside Erlang.mk.

**Comment by essen** [comment]
What do you think? Should Erlang.mk defer all Hex related work to a separate plugin (loaded automatically if needed)?

**Comment by glejeune** [comment]
@elbrujohalcon in hexpm.mk, == is the default.

**Comment by tsloughter** [comment]
@glejeune it looks like the plugin queries hex.pm for all versions of a package any time it wants to resolve a dependency. Is that the case? Better to move to using a local copy of the hex registry for resolving packages.

**Comment by essen** [comment]
@tsloughter It does that. Not sure why the alternative is better though, stateless is definitely a plus. It's not like it's going to result in many more requests, it's only done when fetching the dependency.

**Comment by tsloughter** [comment]
@essen it cuts the roundtrips in half. Sure it isn't as useful without a local cache of packages as well, but it is faster and cuts down greatly on the requests to the non-cdn part of hex.pm (the hosted api).

**Comment by essen** [comment]
This implementation also starts an Erlang VM for each package to fetch (although with -j it could happen in parallel). It's as naive an implementation as it can get.

**Comment by ericmj** [comment]
I pay for parts of the hex.pm infrastructure myself and would greatly appreciate if you tried the minimize the number of requests, use conditional http requests, and used the CDN instead of the hosted API. Fetching the registry and going through the CDN will also make fetching much faster for you.

**Comment by essen** [comment]
I have no doubts that the plugin can and will be improved over time.

I am a bit dumbfounded by your post though. Is it a bandwidth problem? Is the package info that much bandwidth (compared to a conditional query)? Isn't it just a few bytes? 1kb maybe? Do you pay for bandwidth usage maybe?

Or is it a CPU problem? The server can't keep up with the many requests? (Doubtful considering the plugin is pretty new, and the code currently inside Erlang.mk just hits the CDN directly.)

I have a hard time understanding what could be the issue considering I pay less than 5 euros/month for a dedicated with unlimited bandwidth (only 100Mbps, sure, but still, you can go a long way). Unlimited bandwidth is pretty standard on this side of the Atlantic.

**Comment by ericmj** [comment]
It's not a big deal, I'm just saying that the experience will be better for everyone if you follow what I wrote in my post. The CDN is not only faster than the API, it also has better availability and SLAs where we host is better.

You should definitely go ahead with this version if it makes things easier. I (and I believe @tsloughter too) are just giving tips on how you can improve it.

**Comment by essen** [comment]
Would be much easier to deal with if the registry wasn't a dump of an ets table. Then we wouldn't even need Erlang for this.

**Comment by ericmj** [comment]
We are currently discussing a new format for the registry that does not depend on erlang internals.

https://github.com/hexpm/specifications/issues/3

**Comment by tsloughter** [comment]
But you'll need code for parsing the binary file format. Probably easiest to do that in erlang with bitsyntax :)

**Comment by essen** [comment]
What @tsloughter said.

Besides I really doubt going binary instead of text is going to make the compressed size much smaller. There's plenty reasons to go with binaries, but compressed size ain't one.

Erlang.mk bundles the package index for example, and is about 214k bytes uncompressed, 48k bytes compressed (tar czf). Despite the index being basically a lot of Makefile variables (pkg_cowboy_name = cowboy, pkg_cowboy_repository = https://github.com/.. etc.)

Ultimately the best is always to just provide many different formats (and data sets) and let tools choose the one most adapted for their use case.

**Comment by ericmj** [comment]
> Ultimately the best is always to just provide many different formats (and data sets) and let tools choose the one most adapted for their use case.

For sure, as long as the format is still somewhat efficient compressed. Would you be willing to write a proposal for a format you can use?

**Comment by essen** [comment]
If I did I'd propose something similar to: https://wiki.archlinux.org/index.php/pacman#Database_structure - A .tar.gz containing 1 folder per package each containing 1 or more files, which would have `key = value` lines inside.

Basically how pretty much all Linux and BSD package managers do it.

Right now and in the foreseeable future I don't have much time though, so someone else needs to figure out the details.

Note that in the case Erlang.mk itself, a file like this can be just `include cowboy/desc` dynamically where appropriate. (I do something like this with TOML files for the rework of ninenines.eu, although with a little more post processing because TOML strings are quoted and lists are [a,b,c] instead of just words.) It makes the implementation trivial and using a registry database much more interesting. With a registry like this the implementation would be about 30 lines of code. It wouldn't make sense to keep it separate anymore.

**Comment by glejeune** [comment]
@tsloughter @ericmj as @essen said, the current version of hexpm.mk is very naive and was made to validate, quickly, the concept (and allow to work with my collegues who use hex) We are working on improvements, this will come in a few day. Thanks for your remarks.

**Comment by glejeune** [comment]
@tsloughter @ericmj We have upgraded hexpm.mk. We now use the registry and have added two new targes : hex-update and hex-search

**Comment by essen** [comment]
I have added hexpm.mk to the list of plugins in the documentation. I will close this for now. If there's any need for Erlang.mk improvements past that point, we can deal with it in new tickets. Thanks everyone!

**Pull request closed without merging**
