### PR TITLE
Allow to generate .app.src

### PR DESCRIPTION
**Pull request by jeanparpaillon**
Dependancy between .app and .app.src file is calculated when loading Makefile, because of the use of 'wildcard' function.

This patch allows to generate .app.src file, adding a double-colon rule on .app.src, for instance:
```make
src/$(PROJECT).app.src: my_custom_dep
```

Auto-generated .app file has been tested also.

### CODE REVIEW

**Comment by essen** [comment]
I don't understand what this patch is doing.

**Comment by jeanparpaillon** [comment]
Actually, if you write the following rule to generate .app.src, for instance:
```make
src/$(PROJECT).app.src: src/$(PROJECT).app.src.in
     gen $< > $@
```

It does not work because `ebin/$(PROJECT).app` target is generated before the custom rule is executed. 
Reason: dependancy between `ebin/$(PROJECT).app` and `src/$(PROJECT).app.src` is calculated with `wildcard` function.

My patch makes `ebin/$(PROJECT).app` _always_ depends on `src/$(PROJECT).app.src`, which is a fake rule if .app is auto-generated.

**Comment by jeanparpaillon** [comment]
I've updated the patch, was previously broken, sorry

**Comment by essen** [comment]
From what I understand you should have no problem with generating the .app.src if you were doing it as part of `$(PROJECT).d::` because the `ebin/$(PROJECT).app::` target is run in a separate make invocation and therefore the .app.src will exist there. Did you try that?

**Comment by jeanparpaillon** [comment]
Right, my bad ...

**Comment by essen** [comment]
No worries. :-) Do tell if you get it working this way though.

**Comment by jeanparpaillon** [comment]
I confirm it works with dependancy on $(PROJECT).d

**Comment by essen** [comment]
Cheers!

**Pull request closed without merging**
