### PR TITLE
add mimerl to the index

### PR DESCRIPTION
**Pull request by benoitc**
this patch add mimerl to the index

### CODE REVIEW

**Comment by essen** [comment]
This probably doesn't work, try "make check p=mimerl" to confirm.

There's a script ./pkg_add.sh that can be used, for example:

./pkg_add.sh mimerl git repo master website "Description"

**Comment by benoitc** [comment]
I fixed it. Thanks for the review!

**Comment by benoitc** [comment]
hrm not sure why the circle-ci test crash. Will check that later in the morning...

**Comment by essen** [comment]
There's currently one failing test called dialyzer-apps-only. Probably it.

And appveyor probably won't manage to complete the test suite, unless they fixed it.

**Comment by essen** [comment]
For package addition don't worry about those anyway, if "make check p=mimerl" works, then it's all good.

**Comment by benoitc** [comment]
the `make check` command was working yes :)

**Comment by essen** [comment]
Merged, thanks!

**Comment by benoitc** [comment]
:+1:

**Pull request merged**
