### PR TITLE
Fix invalid link to documentation

### LINKED ISSUE #467: Missing link in app.asciidoc
https://github.com/ninenines/erlang.mk/blob/master/doc/src/guide/relx.asciidoc

for memory, too

### PR DESCRIPTION
**Pull request by crownedgrouse**
fix #467

### CODE REVIEW

**Comment by essen** [comment]
Merged, thanks!

**Comment by essen** [comment]
Actually I most likely will broke it again very soon, and won't be able to fix it. This is due to the substandard asciidoc support on Github. You should switch to http://erlang.mk for reading the documentation (links are broken THERE because of a change I did yesterday, I am fixing it now and this will break github).

**Comment by crownedgrouse** [comment]
OK, so what about using a minimal Wiki on github with links to http://erlang.mk , instead ? And a simple cheat sheet in README.md like #370 is proposing may be good. MHO

**Comment by crownedgrouse** [comment]
I precise my thoughts : wiki on github for experimental/master features and a link to http://erlang.mk for things written in marble / official stable documentation.

**Comment by essen** [comment]
There's no difference between master and stable in this project. Documenting experimental features on the wiki would still make them documented and that's not something we want. There's very little of those anyway. Finally there's already a link to erlang.mk at the top of the repository and to the guide in the README.

**Comment by essen** [comment]
Ah, I see, README is still old links.

**Comment by crownedgrouse** [comment]
yes, this is why people, like me, are looking at documentation in github instead of http://erlang.mk

**Comment by crownedgrouse** [comment]
cheat sheet would be nice anyway, and a heading global link to http://erlang.mk documentation would be sufficient , instead many 'Check out our upcoming user guide!' ... but a personal feeling.

**Comment by essen** [comment]
The documentation is slowly phasing out the old README, which explains why things are the way they are now. But it should be time to rework it now. I will do it today.

A cheat sheet would be nice, and will be added at some point. `make help` is the best alternative for now.

**Pull request merged**
