### PR TITLE
add snappyer to index

### PR DESCRIPTION
**Pull request by zmstone**

### CODE REVIEW

**Comment by essen** [comment]
Thanks, I'll check and merge it now. Sorry for the delay, Github has sucked horribly at sending me emails these past few weeks.

**Comment by essen** [comment]
Here it doesn't compile. I got an infinite loop; possibly because you set `C_SRC_DIR = $(CURDIR)`.

**Comment by zmstone** [comment]
moved C source code to c_src.
now it should work without NO_AUTOPATCH

**Comment by essen** [comment]
Thanks. I will try again tomorrow.

**Comment by essen** [comment]
Merged this time. Thanks!

**Pull request closed without merging**
