### PR TITLE
Improve the customisation of edoc, with default values

### PR DESCRIPTION
**Pull request by jeanparpaillon**
edoc options are set through:
- default values (proplists): 
  - {subpackages, false}
  - {source_path, ALL_APPS_DIRS + ALL_DEPS_DIRS}
- 'source_path' can be overriden with EDOC_SRC_DIRS
- all options can be overriden with EDOC_OPTS

### CODE REVIEW

**Comment by essen** [comment]
Looks sensible, just one question. Why put single quotes and then convert to list? If there's a good reason, should put a comment above the .erl block.

**Comment by jeanparpaillon** [comment]
Just updated the pr with a comment on why using single quotes instead of doubles.
Basically, a problem of double-quote escaping. There may be a solution but I have not found it ;)

**Comment by essen** [comment]
Not quite sure about `$(ALL_DEPS_DIRS)`. Also, this needs tests. :-)

**Comment by essen** [comment]
I have merged and did a few tweaks after, and added a test. I don't think there should be any path by default so I removed them. Thanks!

**Pull request closed without merging**
